[package]
name = "embedkv"
edition = "2021"
description = "A compact, block-based embedded key-value store designed for constrained storage environments such as microcontrollers, UEFI, and small flash devices."

license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "embedkv"
path = "src/lib.rs"

[[test]]
name = "compat"
path = "tests/compat.rs"
